### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Blueberryy** [TF2Maps/sourcemod-feedbackround#2]

**Comment by ns-phennessy** [comment]
Are you asking for localization? This could be a feature we can add but we would need native speakers to do translation for us.

**Comment by neilstottler** [comment]
not really sure what's this about since there is no description.

**Comment by Blueberryy** [comment]
> not really sure what's this about since there is no description.

There's literally only one thing that shows to player and this is chat messages of plugin.
I hope they can be translated sometime later
